### ISSUE TITLE
Dependency Error clm_ProgressBar & Usage Question

### ISSUE THREAD

**Issue by ThisBacoff** [PetrisGR/FiveM-CaptureTheArea#2]
Hello, when I run the script, nothing happens, however, I created a zone with Polyzone that I added in the config, I also noticed that I had an error in the console:
![image](https://github.com/user-attachments/assets/003c99af-5b13-4aa3-9793-cee28405c0f9)

**Comment by PetrisGR** [comment]
Hello! You're missing a dependency: https://github.com/Daudeuf/clm_ProgressBar

**Comment by ThisBacoff** [comment]
I checked, I have it, I have the impression that the files of this dependency have been modified and no longer correspond to those in your script, for example the file: clm_progressbar/class no longer exists in the script. 

I also had another question, how do I start a capture?

**Comment by PetrisGR** [comment]
Fixed on v1.0.1. Thanks for noticing.

You can start a capture the area event with 3 ways:

1. Using the export StartEvent
2. Using the command "startcapturethearea"
3. Automatically on scheduled times

If all configured correctly, once you start it, you will understand how it works as soon as you go to its location and try it out.
